# PYPOWER PROJECT : CURRENCY CONVERSION
# GUI BASED PROJECT

IMPORT
TKINTER
AS
TK
FROM
TKINTER
IMPORT *
IMPORT
TKINTER.MESSAGEBOX
ROOT = TK.TK()
ROOT.TITLE("GUI : CURRENCY CONVERSION")

TOPS = FRAME(ROOT, BG='#663300', PADY=2, WIDTH=1850, HEIGHT=100, RELIEF="RIDGE")
TOPS.GRID(ROW=0, COLUMN=0)

HEADLABEL = TK.LABEL(TOPS, FONT=('LATO BLACK', 19, 'BOLD'), TEXT='      PYPOWER PROJECT   :    CURRENCY CONVERTER  ',
                     BG='#663300', FG='WHITE')
HEADLABEL.GRID(ROW=1, COLUMN=0, STICKY=W)

VARIABLE1 = TK.STRINGVAR(ROOT)
VARIABLE2 = TK.STRINGVAR(ROOT)

VARIABLE1.SET("CURRENCY")
VARIABLE2.SET("CURRENCY")

DEF
REALTIMECURRENCYCONVERSION():
FROM
FOREX_PYTHON.CONVERTER
IMPORT
CURRENCYRATES
C = CURRENCYRATES()

FROM_CURRENCY = VARIABLE1.GET()
TO_CURRENCY = VARIABLE2.GET()

IF(AMOUNT1_FIELD.GET() == ""):
TKINTER.MESSAGEBOX.SHOWINFO("ERROR !!", "AMOUNT NOT ENTERED.\N PLEASE A VALID AMOUNT.")

ELIF(FROM_CURRENCY == "CURRENCY"
OR
TO_CURRENCY == "CURRENCY"):
TKINTER.MESSAGEBOX.SHOWINFO("ERROR !!", "CURRENCY NOT SELECTED.\N PLEASE SELECT FROM AND TO CURRENCY FORM MENU.")

ELSE:
NEW_AMT = C.CONVERT(FROM_CURRENCY, TO_CURRENCY, FLOAT(AMOUNT1_FIELD.GET()))
NEW_AMOUNT = FLOAT("{:.4F}".FORMAT(NEW_AMT))
AMOUNT2_FIELD.INSERT(0, STR(NEW_AMOUNT))

DEF
CLEAR_ALL():
AMOUNT1_FIELD.DELETE(0, TK.END)
AMOUNT2_FIELD.DELETE(0, TK.END)

CURRENYCODE_LIST = ["INR", "USD", "CAD", "CNY", "DKK", "EUR"]

ROOT.CONFIGURE(BACKGROUND='#E6E5E5')
ROOT.GEOMETRY("700X400")

LABEL_1 = LABEL(ROOT, FONT=('LATO BLACK', 27, 'BOLD'), TEXT="", PADX=2, PADY=2, BG="#E6E5E5", FG="BLACK")
LABEL_1.GRID(ROW=1, COLUMN=0, STICKY=W)

LABEL1 = TK.LABEL(ROOT, FONT=('LATO BLACK', 15, 'BOLD'), TEXT="\T    AMOUNT  :  ", BG="#E6E5E5", FG="BLACK")
LABEL1.GRID(ROW=2, COLUMN=0, STICKY=W)

LABEL1 = TK.LABEL(ROOT, FONT=('LATO BLACK', 15, 'BOLD'), TEXT="\T    FROM CURRENCY  :  ", BG="#E6E5E5", FG="BLACK")
LABEL1.GRID(ROW=3, COLUMN=0, STICKY=W)

LABEL1 = TK.LABEL(ROOT, FONT=('LATO BLACK', 15, 'BOLD'), TEXT="\T    TO CURRENCY  :  ", BG="#E6E5E5", FG="BLACK")
LABEL1.GRID(ROW=4, COLUMN=0, STICKY=W)

LABEL1 = TK.LABEL(ROOT, FONT=('LATO BLACK', 15, 'BOLD'), TEXT="\T    CONVERTED AMOUNT  :  ", BG="#E6E5E5", FG="BLACK")
LABEL1.GRID(ROW=8, COLUMN=0, STICKY=W)

LABEL_1 = LABEL(ROOT, FONT=('LATO BLACK', 7, 'BOLD'), TEXT="", PADX=2, PADY=2, BG="#E6E5E5", FG="BLACK")
LABEL_1.GRID(ROW=5, COLUMN=0, STICKY=W)

LABEL_1 = LABEL(ROOT, FONT=('LATO BLACK', 7, 'BOLD'), TEXT="", PADX=2, PADY=2, BG="#E6E5E5", FG="BLACK")
LABEL_1.GRID(ROW=7, COLUMN=0, STICKY=W)

FROMCURRENCY_OPTION = TK.OPTIONMENU(ROOT, VARIABLE1, *CURRENYCODE_LIST)
TOCURRENCY_OPTION = TK.OPTIONMENU(ROOT, VARIABLE2, *CURRENYCODE_LIST)

FROMCURRENCY_OPTION.GRID(ROW=3, COLUMN=0, IPADX=45, STICKY=E)
TOCURRENCY_OPTION.GRID(ROW=4, COLUMN=0, IPADX=45, STICKY=E)

AMOUNT1_FIELD = TK.ENTRY(ROOT)
AMOUNT1_FIELD.GRID(ROW=2, COLUMN=0, IPADX=28, STICKY=E)

AMOUNT2_FIELD = TK.ENTRY(ROOT)
AMOUNT2_FIELD.GRID(ROW=8, COLUMN=0, IPADX=31, STICKY=E)

LABEL_9 = BUTTON(ROOT, FONT=('ARIAL', 15, 'BOLD'), TEXT="   CONVERT  ", PADX=2, PADY=2, BG="BLUE", FG="WHITE",
                 COMMAND=REALTIMECURRENCYCONVERSION)
LABEL_9.GRID(ROW=6, COLUMN=0)

LABEL_1 = LABEL(ROOT, FONT=('LATO BLACK', 7, 'BOLD'), TEXT="", PADX=2, PADY=2, BG="#E6E5E5", FG="BLACK")
LABEL_1.GRID(ROW=9, COLUMN=0, STICKY=W)

LABEL_9 = BUTTON(ROOT, FONT=('ARIAL', 15, 'BOLD'), TEXT="   CLEAR ALL  ", PADX=2, PADY=2, BG="WHITE", FG="RED",
                 COMMAND=CLEAR_ALL)
LABEL_9.GRID(ROW=10, COLUMN=0)

ROOT.MAINLOOP()